### ISSUE TITLE
Issue with neovim/Rust Analyzer on 1.0.61

### ISSUE THREAD

**Issue by jszwedko** [dtolnay/anyhow#255]
<!--  ❤️  -->

Hi all!

We seem to be having an issue with Rust Analyzer after the upgrade of 1.0.60 to 1.0.61 in https://github.com/vectordotdev/vector . We see the following output in the neovim LSP:

```
[ERROR][2022-08-11 12:46:36] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR project_model::workspace] cyclic deps: vector_config_macros(CrateId(762)) -> vector_config(CrateId(758)), alternative path: vector_config(CrateId(758)) -> vector_config_macros(CrateId(762))\n"
[ERROR][2022-08-11 12:46:36] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR project_model::workspace] cyclic deps: vrl_stdlib(CrateId(778)) -> vrl(CrateId(768)), alternative path: vrl(CrateId(768)) -> vrl_stdlib(CrateId(778))\n"
[ERROR][2022-08-11 12:46:42] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR rust_analyzer::lsp_utils] failed to run build scripts\n\nerror[E0554]: `#![feature]` may not be used on the stable release channel\n   --> /Users/jesse.szwedko/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.61/src/lib.rs:214:32\n    |\n214 | #![cfg_attr(backtrace, feature(backtrace))]\n    |                                ^^^^^^^^^\n\n\nerror: aborting due to previous error\n\n\nFor more information about this error, try `rustc --explain E0554`.\n\nerror: could not compile `anyhow` due to 2 previous errors\n\n\n"      [ERROR][2022-08-11 12:46:42] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR project_model::workspace] cyclic deps: vector_config_macros(CrateId(762)) -> vector_config(CrateId(758)), alternative path: vector_config(CrateId(758)) -> vector_config_macros(CrateId(762))\n"
[ERROR][2022-08-11 12:46:42] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR project_model::workspace] cyclic deps: vrl_stdlib(CrateId(778)) -> vrl(CrateId(768)), alternative path: vrl(CrateId(768)) -> vrl_stdlib(CrateId(778))\n"
[ERROR][2022-08-11 12:47:51] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR rust_analyzer::lsp_utils] failed to run build scripts\n\nerror[E0554]: `#![feature]` may not be used on the stable release channel\n   --> /Users/jesse.szwedko/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.61/src/lib.rs:214:32\n    |\n214 | #![cfg_attr(backtrace, feature(backtrace))]\n    |                                ^^^^^^^^^\n\n\nerror: aborting due to previous error\n\n\nFor more information about this error, try `rustc --explain E0554`.\n\nerror: could not compile `anyhow` due to 2 previous errors\n\n\n"      [START][2022-08-11 12:50:35] LSP logging initiated                                                                                                                                                                                                                                                                         [ERROR][2022-08-11 12:50:39] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR project_model::workspace] cyclic deps: vector_config_macros(CrateId(762)) -> vector_config(CrateId(758)), alternative path: vector_config(CrateId(758)) -> vector_config_macros(CrateId(762))\n"
[ERROR][2022-08-11 12:50:39] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR project_model::workspace] cyclic deps: vrl_stdlib(CrateId(778)) -> vrl(CrateId(768)), alternative path: vrl(CrateId(768)) -> vrl_stdlib(CrateId(778))\n"
[ERROR][2022-08-11 12:53:28] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR project_model::workspace] cyclic deps: vector_config_macros(CrateId(762)) -> vector_config(CrateId(758)), alternative path: vector_config(CrateId(758)) -> vector_config_macros(CrateId(762))\n"
[ERROR][2022-08-11 12:53:28] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "[ERROR project_model::workspace] cyclic deps: vrl_stdlib(CrateId(778)) -> vrl(CrateId(768)), alternative path: vrl(CrateId(768)) -> vrl_stdlib(CrateId(778))\n"
```

I see there is another issue filed recently about a regression, https://github.com/dtolnay/anyhow/issues/253, but that appears to be a different issue.

I believe the relevant neovim configuration is:

```
  local nvim_lsp = require('lspconfig')

  -- Use an on_attach function to only map the following keys
  -- after the language server attaches to the current buffer
  local on_attach = function(client, bufnr)
    local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
    local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

    -- Enable completion triggered by <c-x><c-o>
    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap=true, silent=true }

    -- See `:help vim.lsp.*` for documentation on any of the below functions
    buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts) buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)                                                                                                               buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)                                                                                                                                                                                                                                        buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)                                                                                                                                                                                                                                           buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)                                                                                                                                                                                                                                                   buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)                                                                                                                                                                                                                           buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)                                                                                                                                                                                                                                             buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)                                                                                                                                                                                                                                             buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)                                                                                                                                                                                                                                     buf_set_keymap('n', '<space>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', opts)                                                                                                                                                                                                                                           end
                                                                                                                                                                                                                                                                                                                             -- Add additional capabilities supported by nvim-cmp
  local capabilities = vim.lsp.protocol.make_client_capabilities()                                                                                                                                                                                                                                                           capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              nvim_lsp.rust_analyzer.setup {
    on_attach = on_attach,
    capabilities = capabilities,                                                                                                                                                                                                                                                                                               settings = {
        ["rust-analyzer"] = {                                                                                                                                                                                                                                                                                                          checkOnSave = {
              extraArgs = {"--target-dir", "/tmp/rust-analyzer"}                                                                                                                                                                                                                                                                       }
        }                                                                                                                                                                                                                                                                                                                      },
    flags = {
      debounce_text_changes = 150,
    }
  }
```

Let me know if you need any additional information to help reproduce!

**Comment by jszwedko** [comment]
```
$ rust-analyzer --version
rust-analyzer 0.0.0 (634cfe3d7 2022-08-07)
```

**Comment by dtolnay** [comment]
This looks like a duplicate of #250.

**Comment by jszwedko** [comment]
Doh, yes, I think you are right. I missed that when searching. Thanks for the pointer! I'll follow along there and the linked rust-analyzer issue.
