### ISSUE TITLE
Rust analiser keeps prompting errors when upgrade to 1.65 stable toolchain

### ISSUE THREAD

**Issue by CoorFun** [dtolnay/anyhow#288]
version = "1.0.66"

```bash
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.66/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.66/src/lib.rs:214:61
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                                             ^^^^^^^^^^^
```

**Comment by dtolnay** [comment]
Duplicate of #250. It's a rust-analyzer bug that was fixed a long time ago.
