### ISSUE TITLE
Doesn't compile on rustc 1.63.0 OSX 12.6 Intel

### ISSUE THREAD

**Issue by danielcontro** [dtolnay/anyhow#273]
when I try to build an empty project with just anyhow as a dependency it gives the following compiling errors:
```
❯ cargo build
   Compiling anyhow v1.0.65
error[E0407]: method `provide` is not a member of trait `StdError`
   --> $CARGO_HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.65/src/context.rs:131:5
    |
131 | /     fn provide<'a>(&'a self, demand: &mut Demand<'a>) {
132 | |         self.error.provide(demand);
133 | |     }
    | |_____^ not a member of trait `StdError`

error[E0407]: method `provide` is not a member of trait `StdError`
   --> $CARGO_HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.65/src/context.rs:145:5
    |
145 | /     fn provide<'a>(&'a self, demand: &mut Demand<'a>) {
146 | |         demand.provide_ref(self.error.backtrace());
147 | |         self.error.provide(demand);
148 | |     }
    | |_____^ not a member of trait `StdError`
```

I'm on a 2018 MacBook Pro 13" Intel with OSX 12.6, rustc 1.63.0, cargo 1.63.

**Comment by dtolnay** [comment]
I am not able to reproduce this. Possibly you have an old version of rust-analyzer or intellij-rust screwing up the target directory (old versions of those tend to do that).

```console
% cargo --version
cargo 1.63.0 (fd9c4297c 2022-07-01)

% rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)

% cargo init
     Created binary (application) package

% cargo add anyhow
    Updating crates.io index
      Adding anyhow v1.0.65 to dependencies.
             Features:
             + std
             - backtrace

% cargo build
    Updating crates.io index
  Downloaded anyhow v1.0.65
  Downloaded 1 crate (43.6 KB) in 0.23s
   Compiling anyhow v1.0.65
   Compiling repro v0.1.0
    Finished dev [unoptimized + debuginfo] target(s) in 1.49s
```

If you have repro steps that reliably reproduce this, we can reopen.

**Comment by HerringtonDarkholme** [comment]
I have met the similar problem and the solution is to clear the target directory by `cargo clean` and it successfully compiles then.
