### ISSUE TITLE
could not find `addr_of` in `ptr`

### ISSUE THREAD

**Issue by mrLSD** [dtolnay/anyhow#148]
`anyhow` used as dependency of some of other dependency in project.
And I have go error:
```
error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.40/src/error.rs:606:14
    |
606 |         ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
    |              ^^^^^^^ could not find `addr_of` in `ptr`

error[E0433]: failed to resolve: could not find `addr_of` in `ptr`
   --> /home/evgeny/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.40/src/error.rs:647:22
    |
647 |                 ptr::addr_of!((*unerased.as_ptr())._object) as *mut E,
    |                      ^^^^^^^ could not find `addr_of` in `ptr`

error: aborting due to 2 previous errors

```
* rustc: `nightly-2021-01-30`
* target: `wasm32-unknown-unknown`
* OS: `ubuntu-16.04`

**Comment by soenkeliebau** [comment]
I had the same issue, but just with nightly, stable still worked fine and after an update it works with 1.53.0-nightly (07e0e2ec2 2021-03-24) as well.

**Comment by mrLSD** [comment]
I just fixed it with `anyhow = "=1.0.39"`

But for my current library, I can't upgrade it from my toolchain `nightly-2021-01-31`

**Comment by dtolnay** [comment]
Closing as a duplicate of #146. This crate does not support old nightlies; the expectation is that if you are using a nightly toolchain, then you are remaining on top of recent nightly changes.

**Comment by mrLSD** [comment]
@dtolnay thanks for your response.
And another solution - just use a fixed version of `anyhow` if it's impossible to upgrade.
